services:
  postgres:
    image: postgres:16-alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      main:
        aliases:
          - postgres

  backend:
    build:
      context: .
    container_name: backend
    restart: always
    depends_on:
      - postgres
    env_file:
      - .env.docker
    environment:
      PORT: 5050
    ports:
      - "5050:5050"
    networks:
      main:
        aliases:
          - backend

volumes:
  postgres_data:

networks:
  main:
